# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class PostmanTui < Formula
  desc "Simple HTTP Request TUI Tool!"
  homepage "https://github.com/hatsu38/postman-tui"
  version "0.0.5"
  license "MIT"
  bottle :unneeded

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/hatsu38/postman-tui/releases/download/v0.0.5/postman-tui_0.0.5_Darwin_x86_64.tar.gz"
      sha256 "1a84a34044d8a2dca6e7803944ede85abe3780677f6ab151756267279f823fee"
    end
    if Hardware::CPU.arm?
      url "https://github.com/hatsu38/postman-tui/releases/download/v0.0.5/postman-tui_0.0.5_Darwin_arm64.tar.gz"
      sha256 "43e1c478e75e46b7dd46425d3115b2fabe4c19b7cb7c6fc6a6e8f961d2815bb8"
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/hatsu38/postman-tui/releases/download/v0.0.5/postman-tui_0.0.5_Linux_x86_64.tar.gz"
      sha256 "f690aaad88f1e6dee1e11da569d8d89ecf5bca37c252c7154542df1d04a949e7"
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/hatsu38/postman-tui/releases/download/v0.0.5/postman-tui_0.0.5_Linux_arm64.tar.gz"
      sha256 "cad5f4f10ff6be4c308f285c7f718dceb653bd4ffee6a1d33724f9e2b5551f6c"
    end
  end

  def install
    bin.install "postman-tui"
  end

  test do
    system "#{bin}/postman-tui"
  end
end
